language: python

python:
  - 2.7

install:
  - sudo apt-get install -y python-software-properties
  - sudo apt-add-repository -y ppa:git-core/ppa
  - sudo apt-add-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq

  # gpxpy
  - pip install -r requirements.txt

  # pysqlite
  - pip install pysqlite

  # Spatialiate
  - sudo apt-get install -y libproj-dev libgeos-dev libspatialite-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libspatialite.so /usr/lib/libspatialite.so

script: python setup.py test
